import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero'
import Slider from '@/components/Slider'
import { SliderData } from '../components/SliderData';
import Instagram from '@/components/Instagram';

export default function Home() {
  return (    
    <div>
      {/* Rendre le titre hero dynamique */}
      <Head>
        <title>Photography Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='Photographies' message='Je capture des moments de vie'/>   
      <Slider slides={SliderData}/>
      <Instagram/>
    </div>     
  )
}
